"""补天报告渲染器共享的中文展示标签。"""

SECRET_TYPE_LABELS = {
    "aws_access_key": "AWS 访问密钥",
    "aws_secret_key": "AWS Secret Key",
    "aws_session_token": "AWS 临时会话 Token",
    "gcp_service_account": "GCP 服务账号",
    "gcp_api_key": "GCP API Key",
    "gcp_oauth_token": "GCP OAuth Token",
    "azure_client_secret": "Azure 客户端密钥",
    "azure_connection_string": "Azure 连接字符串",
    "azure_sas_token": "Azure SAS Token",
    "aliyun_access_key": "阿里云 AccessKey",
    "aliyun_secret_key": "阿里云 Secret",
    "tencent_secret_id": "腾讯云 SecretId",
    "huawei_access_key": "华为云 Access Key",
    "huawei_secret_key": "华为云 Secret Key",
    "oracle_api_key": "Oracle API Key",
    "digitalocean_token": "DigitalOcean Token",
    "linode_api_key": "Linode API Key",
    "vultr_api_key": "Vultr API Key",
    "cloudflare_api_key": "Cloudflare API Key",
    "cloudflare_api_token": "Cloudflare API Token",
    "cloudflare_origin_ca": "Cloudflare Origin CA Key",
    "heroku_api_key": "Heroku API Key",
    "github_fine_grained_pat": "GitHub fine-grained PAT",
    "github_token": "GitHub Token",
    "github_oauth": "GitHub OAuth Token",
    "github_app_token": "GitHub App Token",
    "github_refresh_token": "GitHub Refresh Token",
    "gitlab_token": "GitLab Token",
    "gitlab_runner_token": "GitLab Runner Token",
    "gitlab_deploy_token": "GitLab Deploy Token",
    "hashicorp_vault_token": "HashiCorp Vault Token",
    "pulumi_token": "Pulumi Token",
    "groq_api_key": "Groq API Key",
    "vercel_token": "Vercel Token",
    "netlify_token": "Netlify Token",
    "railway_token": "Railway Token",
    "render_token": "Render Token",
    "snyk_token": "Snyk Token",
    "resend_api_key": "Resend API Key",
    "clerk_secret_key": "Clerk Secret Key",
    "supabase_service_role_key": "Supabase service-role key",
    "algolia_admin_key": "Algolia Admin API Key",
    "slack_token": "Slack Token",
    "slack_webhook": "Slack Webhook",
    "discord_token": "Discord Token",
    "discord_bot_token": "Discord Bot Token",
    "discord_webhook": "Discord Webhook",
    "stripe_secret_key": "Stripe 密钥",
    "stripe_publishable_key": "Stripe Publishable Key",
    "stripe_restricted_key": "Stripe Restricted Key",
    "twilio_api_key": "Twilio API Key",
    "twilio_account_sid": "Twilio Account SID",
    "sendgrid_api_key": "SendGrid API Key",
    "mailgun_api_key": "Mailgun API Key",
    "mailchimp_api_key": "Mailchimp API Key",
    "square_access_token": "Square Access Token",
    "square_oauth_secret": "Square OAuth Secret",
    "shopify_token": "Shopify Token",
    "paypal_bearer_token": "PayPal Bearer Token",
    "braintree_token": "Braintree Token",
    "firebase_key": "Firebase Key",
    "datadog_api_key": "Datadog API Key",
    "datadog_app_key": "Datadog App Key",
    "newrelic_key": "New Relic Key",
    "pagerduty_token": "PagerDuty Token",
    "grafana_api_key": "Grafana API Key",
    "npm_token": "npm Token",
    "npmrc_auth_token": "npm registry Token",
    "docker_hub_token": "Docker Hub Token",
    "terraform_token": "Terraform Cloud Token",
    "circleci_token": "CircleCI Token",
    "travis_token": "Travis CI Token",
    "buildkite_token": "Buildkite Token",
    "jenkins_token": "Jenkins Token",
    "jfrog_token": "JFrog Token",
    "postman_api_key": "Postman API Key",
    "openai_key": "OpenAI API Key",
    "anthropic_key": "Anthropic API Key",
    "huggingface_token": "Hugging Face Token",
    "replicate_token": "Replicate Token",
    "pypi_token": "PyPI Token",
    "rubygems_token": "RubyGems Token",
    "nuget_api_key": "NuGet API Key",
    "sonar_token": "Sonar Token",
    "atlassian_token": "Atlassian / Jira Token",
    "notion_token": "Notion Token",
    "linear_api_key": "Linear API Key",
    "airtable_api_key": "Airtable API Key",
    "asana_token": "Asana Token",
    "fastly_api_key": "Fastly API Key",
    "ngrok_token": "ngrok Token",
    "sentry_token": "Sentry Token",
    "databricks_token": "Databricks Token",
    "mongodb_connection": "MongoDB 连接字符串",
    "postgres_connection": "PostgreSQL 连接字符串",
    "mysql_connection": "MySQL 连接字符串",
    "redis_connection": "Redis 连接字符串",
    "amqp_connection": "AMQP 连接字符串",
    "kafka_connection": "Kafka / Confluent 凭证",
    "private_key": "私钥",
    "generic_password": "疑似密码",
    "generic_api_key": "疑似 API Key",
    "generic_token": "疑似 Token",
    "bearer_token": "Bearer Token",
    "generic_secret": "疑似 Secret",
    "base64_secret": "疑似 Base64 编码密钥",
    "connection_string": "疑似连接字符串",
    "basic_auth_url": "URL 内嵌账号密码",
    "netrc_password": ".netrc 机器密码",
    "encryption_key": "疑似加密密钥",
    "webhook_url": "Webhook URL",
    "jwt_token": "JWT Token",
    "generic_sk_key": "LLM/API 密钥 (sk-)",
}

SENSITIVE_TYPE_LABELS = {
    "env_file": "环境变量文件",
    "envrc": ".envrc 环境配置",
    "npmrc": "npm 配置文件",
    "pypirc": "PyPI 发布配置",
    "netrc": ".netrc 凭据文件",
    "gem_credentials": "RubyGems 凭据",
    "private_key": "私钥或证书文件",
    "ssh_key": "SSH 密钥",
    "kubeconfig": "Kubernetes kubeconfig",
    "docker_cfg": "Docker 凭据配置",
    "database": "本地数据库或转储文件",
    "credentials": "凭证文件",
    "aws_credentials": "AWS 凭据文件",
    "gcp_credentials": "GCP 凭据文件",
    "azure_credentials": "Azure 凭据文件",
    "terraform_state": "Terraform 状态文件",
    "terraform_vars": "Terraform 变量文件",
    "ansible_vault": "Ansible Vault 密码文件",
    "ci_secrets": "CI secrets 配置",
    "gradle_properties": "Gradle 配置文件",
    "maven_settings": "Maven settings.xml",
    "log": "日志文件",
    "dump": "数据导出或转储文件",
    "app_config": "应用配置文件",
    "backup": "备份文件",
    "history": "命令历史文件",
}
